---
language: ruby
rvm:
  - 2.1
  - 2.2
sudo: false
cache: bundler
before_script:
  - bundle exec rake test_app
script:
  - bundle exec rspec spec
env:
  global:
    secure: PzlQd6QwHoJUiGup3hJW0z59HfFaBnMQpe5sIMtbwFGtkJdIHd5NRH6PAefQpXfr+ukFPzstimS3JjorKRuS0VOjvyPlazhr+tVBLrvoyFJJKoFreWvryKZmTSbnrhVIlmz9VpI2bT2A1pvlR+pb/mFp1HciMifyFeqG7I+4qifKt+7CLMkTNhXWjbClaDMW5P2HCJEqfONJavciOhPdnsgWjbFM2k6e/JNlPI75xDHRF0i/Yu3cY2gO8vY/CzVpZrWlvj0O6e3K+W4Ew6yGRNDVIYokmP3wfWmGRCmjDkY+23FJCFCK+jUeA6wrGLfH8SdgbaN2D/9WxshIAhJFr0dao0oQxJibDAPF9+4yXda47jJG59SEBPLInWQRoKT00U+JRhtmBRybDqpRyr+SJEeTZMpaDMxu9mCZbP2Ayvsca/JgslIEhm7FNsEV6/Yq9VE4BdpqvY07/h5Tt/oT8Jtz3RQCCj3syN0RdFIMjh9p+Zt/kOoNy2jzoOoNVKNuS8xziDdzlnjZ6gsXaopr/ZiGoCcUglw3HS49A1IunZn/pSBErH95ueRlnSFDKzCt1w9NzQRdaBHR16ZlhMO0FsdxGr7R0v+WSg4mmZdRi1TikQ6WC1l2csgTZiqGcdmHT4AgUav6S8y02OsQInaT3rBEY89ZUL/8aTovTSTVT2U=
